# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kokoro/agent/presentation/v1/agent_presentation.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kokoro.agent.presentation.v1.agent_presentation_pb2 as kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2


class AgentPresentationService(Protocol):
    async def check_active(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def pull_candidate_batches(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def acknowledge_candidate_admissions(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def quarantine_candidate_admission(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_delivery_status(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AgentPresentationServiceASGIApplication(ConnectASGIApplication[AgentPresentationService]):
    def __init__(self, service: AgentPresentationService | AsyncGenerator[AgentPresentationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kokoro.agent.presentation.v1.AgentPresentationService/CheckActive": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckActive",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_active,
                ),
                "/kokoro.agent.presentation.v1.AgentPresentationService/PullCandidateBatches": Endpoint.unary(
                    method=MethodInfo(
                        name="PullCandidateBatches",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.pull_candidate_batches,
                ),
                "/kokoro.agent.presentation.v1.AgentPresentationService/AcknowledgeCandidateAdmissions": Endpoint.unary(
                    method=MethodInfo(
                        name="AcknowledgeCandidateAdmissions",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.acknowledge_candidate_admissions,
                ),
                "/kokoro.agent.presentation.v1.AgentPresentationService/QuarantineCandidateAdmission": Endpoint.unary(
                    method=MethodInfo(
                        name="QuarantineCandidateAdmission",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.quarantine_candidate_admission,
                ),
                "/kokoro.agent.presentation.v1.AgentPresentationService/GetDeliveryStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDeliveryStatus",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_delivery_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.agent.presentation.v1.AgentPresentationService"


class AgentPresentationServiceClient(ConnectClient):
    async def check_active(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckActive",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def pull_candidate_batches(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PullCandidateBatches",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def acknowledge_candidate_admissions(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AcknowledgeCandidateAdmissions",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def quarantine_candidate_admission(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QuarantineCandidateAdmission",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_delivery_status(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDeliveryStatus",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class AgentPresentationServiceSync(Protocol):
    def check_active(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def pull_candidate_batches(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def acknowledge_candidate_admissions(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def quarantine_candidate_admission(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_delivery_status(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AgentPresentationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AgentPresentationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kokoro.agent.presentation.v1.AgentPresentationService/CheckActive": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckActive",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_active,
                ),
                "/kokoro.agent.presentation.v1.AgentPresentationService/PullCandidateBatches": EndpointSync.unary(
                    method=MethodInfo(
                        name="PullCandidateBatches",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.pull_candidate_batches,
                ),
                "/kokoro.agent.presentation.v1.AgentPresentationService/AcknowledgeCandidateAdmissions": EndpointSync.unary(
                    method=MethodInfo(
                        name="AcknowledgeCandidateAdmissions",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.acknowledge_candidate_admissions,
                ),
                "/kokoro.agent.presentation.v1.AgentPresentationService/QuarantineCandidateAdmission": EndpointSync.unary(
                    method=MethodInfo(
                        name="QuarantineCandidateAdmission",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.quarantine_candidate_admission,
                ),
                "/kokoro.agent.presentation.v1.AgentPresentationService/GetDeliveryStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDeliveryStatus",
                        service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_delivery_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.agent.presentation.v1.AgentPresentationService"


class AgentPresentationServiceClientSync(ConnectClientSync):
    def check_active(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckActive",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.CheckActiveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def pull_candidate_batches(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PullCandidateBatches",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.PullCandidateBatchesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def acknowledge_candidate_admissions(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AcknowledgeCandidateAdmissions",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.AcknowledgeCandidateAdmissionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def quarantine_candidate_admission(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QuarantineCandidateAdmission",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.QuarantineCandidateAdmissionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_delivery_status(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDeliveryStatus",
                service_name="kokoro.agent.presentation.v1.AgentPresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_agent__presentation__pb2.GetDeliveryStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
