# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kokoro/agent/presentation/v1/presentation.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kokoro.agent.presentation.v1.presentation_pb2 as kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2


class PresentationService(Protocol):
    async def check_active(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def pull_records(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def acknowledge_admissions(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def quarantine_submission(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_delivery_status(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PresentationServiceASGIApplication(ConnectASGIApplication[PresentationService]):
    def __init__(self, service: PresentationService | AsyncGenerator[PresentationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kokoro.agent.presentation.v1.PresentationService/CheckActive": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckActive",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_active,
                ),
                "/kokoro.agent.presentation.v1.PresentationService/PullRecords": Endpoint.unary(
                    method=MethodInfo(
                        name="PullRecords",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.pull_records,
                ),
                "/kokoro.agent.presentation.v1.PresentationService/AcknowledgeAdmissions": Endpoint.unary(
                    method=MethodInfo(
                        name="AcknowledgeAdmissions",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.acknowledge_admissions,
                ),
                "/kokoro.agent.presentation.v1.PresentationService/QuarantineSubmission": Endpoint.unary(
                    method=MethodInfo(
                        name="QuarantineSubmission",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.quarantine_submission,
                ),
                "/kokoro.agent.presentation.v1.PresentationService/GetDeliveryStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDeliveryStatus",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_delivery_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.agent.presentation.v1.PresentationService"


class PresentationServiceClient(ConnectClient):
    async def check_active(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckActive",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def pull_records(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PullRecords",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def acknowledge_admissions(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AcknowledgeAdmissions",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def quarantine_submission(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QuarantineSubmission",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_delivery_status(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDeliveryStatus",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class PresentationServiceSync(Protocol):
    def check_active(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def pull_records(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def acknowledge_admissions(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def quarantine_submission(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_delivery_status(self, request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PresentationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: PresentationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kokoro.agent.presentation.v1.PresentationService/CheckActive": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckActive",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_active,
                ),
                "/kokoro.agent.presentation.v1.PresentationService/PullRecords": EndpointSync.unary(
                    method=MethodInfo(
                        name="PullRecords",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.pull_records,
                ),
                "/kokoro.agent.presentation.v1.PresentationService/AcknowledgeAdmissions": EndpointSync.unary(
                    method=MethodInfo(
                        name="AcknowledgeAdmissions",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.acknowledge_admissions,
                ),
                "/kokoro.agent.presentation.v1.PresentationService/QuarantineSubmission": EndpointSync.unary(
                    method=MethodInfo(
                        name="QuarantineSubmission",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.quarantine_submission,
                ),
                "/kokoro.agent.presentation.v1.PresentationService/GetDeliveryStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDeliveryStatus",
                        service_name="kokoro.agent.presentation.v1.PresentationService",
                        input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusRequest,
                        output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_delivery_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.agent.presentation.v1.PresentationService"


class PresentationServiceClientSync(ConnectClientSync):
    def check_active(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckActive",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.CheckActiveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def pull_records(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PullRecords",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.PullRecordsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def acknowledge_admissions(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AcknowledgeAdmissions",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.AcknowledgeAdmissionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def quarantine_submission(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QuarantineSubmission",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.QuarantineSubmissionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_delivery_status(
        self,
        request: kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDeliveryStatus",
                service_name="kokoro.agent.presentation.v1.PresentationService",
                input=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusRequest,
                output=kokoro_dot_agent_dot_presentation_dot_v1_dot_presentation__pb2.GetDeliveryStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
