# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kokoro/platform/media/v1/media_runtime.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kokoro.platform.media.v1.media_runtime_pb2 as kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2


class MediaRuntimeService(Protocol):
    async def create_agent_image_operation(self, request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def cancel_agent_media_operation(self, request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def recover_media_operation_by_command(self, request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_agent_media_operation(self, request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class MediaRuntimeServiceASGIApplication(ConnectASGIApplication[MediaRuntimeService]):
    def __init__(self, service: MediaRuntimeService | AsyncGenerator[MediaRuntimeService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kokoro.platform.media.v1.MediaRuntimeService/CreateAgentImageOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateAgentImageOperation",
                        service_name="kokoro.platform.media.v1.MediaRuntimeService",
                        input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationRequest,
                        output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_agent_image_operation,
                ),
                "/kokoro.platform.media.v1.MediaRuntimeService/CancelAgentMediaOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="CancelAgentMediaOperation",
                        service_name="kokoro.platform.media.v1.MediaRuntimeService",
                        input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationRequest,
                        output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.cancel_agent_media_operation,
                ),
                "/kokoro.platform.media.v1.MediaRuntimeService/RecoverMediaOperationByCommand": Endpoint.unary(
                    method=MethodInfo(
                        name="RecoverMediaOperationByCommand",
                        service_name="kokoro.platform.media.v1.MediaRuntimeService",
                        input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandRequest,
                        output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.recover_media_operation_by_command,
                ),
                "/kokoro.platform.media.v1.MediaRuntimeService/GetAgentMediaOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAgentMediaOperation",
                        service_name="kokoro.platform.media.v1.MediaRuntimeService",
                        input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationRequest,
                        output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_agent_media_operation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.platform.media.v1.MediaRuntimeService"


class MediaRuntimeServiceClient(ConnectClient):
    async def create_agent_image_operation(
        self,
        request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateAgentImageOperation",
                service_name="kokoro.platform.media.v1.MediaRuntimeService",
                input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationRequest,
                output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def cancel_agent_media_operation(
        self,
        request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelAgentMediaOperation",
                service_name="kokoro.platform.media.v1.MediaRuntimeService",
                input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationRequest,
                output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def recover_media_operation_by_command(
        self,
        request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RecoverMediaOperationByCommand",
                service_name="kokoro.platform.media.v1.MediaRuntimeService",
                input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandRequest,
                output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_agent_media_operation(
        self,
        request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentMediaOperation",
                service_name="kokoro.platform.media.v1.MediaRuntimeService",
                input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationRequest,
                output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class MediaRuntimeServiceSync(Protocol):
    def create_agent_image_operation(self, request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def cancel_agent_media_operation(self, request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def recover_media_operation_by_command(self, request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_agent_media_operation(self, request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class MediaRuntimeServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: MediaRuntimeServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kokoro.platform.media.v1.MediaRuntimeService/CreateAgentImageOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateAgentImageOperation",
                        service_name="kokoro.platform.media.v1.MediaRuntimeService",
                        input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationRequest,
                        output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_agent_image_operation,
                ),
                "/kokoro.platform.media.v1.MediaRuntimeService/CancelAgentMediaOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="CancelAgentMediaOperation",
                        service_name="kokoro.platform.media.v1.MediaRuntimeService",
                        input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationRequest,
                        output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.cancel_agent_media_operation,
                ),
                "/kokoro.platform.media.v1.MediaRuntimeService/RecoverMediaOperationByCommand": EndpointSync.unary(
                    method=MethodInfo(
                        name="RecoverMediaOperationByCommand",
                        service_name="kokoro.platform.media.v1.MediaRuntimeService",
                        input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandRequest,
                        output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.recover_media_operation_by_command,
                ),
                "/kokoro.platform.media.v1.MediaRuntimeService/GetAgentMediaOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAgentMediaOperation",
                        service_name="kokoro.platform.media.v1.MediaRuntimeService",
                        input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationRequest,
                        output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_agent_media_operation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.platform.media.v1.MediaRuntimeService"


class MediaRuntimeServiceClientSync(ConnectClientSync):
    def create_agent_image_operation(
        self,
        request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateAgentImageOperation",
                service_name="kokoro.platform.media.v1.MediaRuntimeService",
                input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationRequest,
                output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CreateAgentImageOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def cancel_agent_media_operation(
        self,
        request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelAgentMediaOperation",
                service_name="kokoro.platform.media.v1.MediaRuntimeService",
                input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationRequest,
                output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.CancelAgentMediaOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def recover_media_operation_by_command(
        self,
        request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RecoverMediaOperationByCommand",
                service_name="kokoro.platform.media.v1.MediaRuntimeService",
                input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandRequest,
                output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.RecoverMediaOperationByCommandResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_agent_media_operation(
        self,
        request: kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentMediaOperation",
                service_name="kokoro.platform.media.v1.MediaRuntimeService",
                input=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationRequest,
                output=kokoro_dot_platform_dot_media_dot_v1_dot_media__runtime__pb2.GetAgentMediaOperationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
