# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kokoro/platform/media/v1/media_canonical.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'kokoro/platform/media/v1/media_canonical.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.kokoro/platform/media/v1/media_canonical.proto\x12\x18kokoro.platform.media.v1\x1a\x1b\x62uf/validate/validate.proto\"\xe5\x02\n\x16ImageTextToImageSpecV1\x12\"\n\rprompt_intent\x18\x01 \x01(\tB\x0b\xbaH\x08r\x06 \x01(\x80\x80\x02\x12U\n\x0c\x61spect_ratio\x18\x02 \x01(\x0e\x32\x33.kokoro.platform.media.v1.CanonicalImageAspectRatioB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00\x12\"\n\x0f\x63\x61ndidate_count\x18\x03 \x01(\rB\t\xbaH\x06*\x04\x18\x04(\x01\x12S\n\x19model_option_revision_ref\x18\x04 \x01(\tB0\xbaH-r+\x10\x01\x18\x80\x02\x32$^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$\x12W\n\routput_format\x18\x05 \x01(\x0e\x32\x34.kokoro.platform.media.v1.CanonicalImageOutputFormatB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00\"\xf4\x01\n\x1e\x43\x61nonicalMediaOperationInputV1\x12\x1f\n\x0e\x63ontract_major\x18\x01 \x01(\rB\x07\xbaH\x04*\x02\x08\x01\x12Q\n\x17\x64\x65\x66inition_revision_ref\x18\x02 \x01(\tB0\xbaH-r+\x10\x01\x18\x80\x02\x32$^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$\x12O\n\x13image_text_to_image\x18\x03 \x01(\x0b\x32\x30.kokoro.platform.media.v1.ImageTextToImageSpecV1H\x00\x42\r\n\x04spec\x12\x05\xbaH\x02\x08\x01*\xb6\x02\n\x19\x43\x61nonicalImageAspectRatio\x12,\n(CANONICAL_IMAGE_ASPECT_RATIO_UNSPECIFIED\x10\x00\x12+\n\'CANONICAL_IMAGE_ASPECT_RATIO_SQUARE_1_1\x10\x01\x12.\n*CANONICAL_IMAGE_ASPECT_RATIO_LANDSCAPE_4_3\x10\x02\x12/\n+CANONICAL_IMAGE_ASPECT_RATIO_LANDSCAPE_16_9\x10\x03\x12-\n)CANONICAL_IMAGE_ASPECT_RATIO_PORTRAIT_3_4\x10\x04\x12.\n*CANONICAL_IMAGE_ASPECT_RATIO_PORTRAIT_9_16\x10\x05*\xc2\x01\n\x1a\x43\x61nonicalImageOutputFormat\x12-\n)CANONICAL_IMAGE_OUTPUT_FORMAT_UNSPECIFIED\x10\x00\x12%\n!CANONICAL_IMAGE_OUTPUT_FORMAT_PNG\x10\x01\x12&\n\"CANONICAL_IMAGE_OUTPUT_FORMAT_JPEG\x10\x02\x12&\n\"CANONICAL_IMAGE_OUTPUT_FORMAT_WEBP\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kokoro.platform.media.v1.media_canonical_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['prompt_intent']._loaded_options = None
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['prompt_intent']._serialized_options = b'\272H\010r\006 \001(\200\200\002'
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['aspect_ratio']._loaded_options = None
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['aspect_ratio']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['candidate_count']._loaded_options = None
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['candidate_count']._serialized_options = b'\272H\006*\004\030\004(\001'
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['model_option_revision_ref']._loaded_options = None
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['model_option_revision_ref']._serialized_options = b'\272H-r+\020\001\030\200\0022$^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$'
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['output_format']._loaded_options = None
  _globals['_IMAGETEXTTOIMAGESPECV1'].fields_by_name['output_format']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_CANONICALMEDIAOPERATIONINPUTV1'].oneofs_by_name['spec']._loaded_options = None
  _globals['_CANONICALMEDIAOPERATIONINPUTV1'].oneofs_by_name['spec']._serialized_options = b'\272H\002\010\001'
  _globals['_CANONICALMEDIAOPERATIONINPUTV1'].fields_by_name['contract_major']._loaded_options = None
  _globals['_CANONICALMEDIAOPERATIONINPUTV1'].fields_by_name['contract_major']._serialized_options = b'\272H\004*\002\010\001'
  _globals['_CANONICALMEDIAOPERATIONINPUTV1'].fields_by_name['definition_revision_ref']._loaded_options = None
  _globals['_CANONICALMEDIAOPERATIONINPUTV1'].fields_by_name['definition_revision_ref']._serialized_options = b'\272H-r+\020\001\030\200\0022$^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$'
  _globals['_CANONICALIMAGEASPECTRATIO']._serialized_start=713
  _globals['_CANONICALIMAGEASPECTRATIO']._serialized_end=1023
  _globals['_CANONICALIMAGEOUTPUTFORMAT']._serialized_start=1026
  _globals['_CANONICALIMAGEOUTPUTFORMAT']._serialized_end=1220
  _globals['_IMAGETEXTTOIMAGESPECV1']._serialized_start=106
  _globals['_IMAGETEXTTOIMAGESPECV1']._serialized_end=463
  _globals['_CANONICALMEDIAOPERATIONINPUTV1']._serialized_start=466
  _globals['_CANONICALMEDIAOPERATIONINPUTV1']._serialized_end=710
# @@protoc_insertion_point(module_scope)
