# Generated by scripts/generate_failure_models.py. DO NOT EDIT.
# Source: contract/openapi/v1/openapi.json sha256=e9f0a543f74dee34212f0ea4fe366d46218268462ac54dce08e41965f34d2d2c
from __future__ import annotations

from typing import Literal, Self

from pydantic import BaseModel, ConfigDict, model_validator

RunErrorCode = Literal[
    "token_budget_exceeded",
    "recursion_limit_exceeded",
    "assembly_failed",
    "enqueue_failed",
    "dispatch_exhausted",
    "contract_incompatible",
    "internal_error",
    "model_unavailable",
    "dependency_unavailable",
    "model_access_denied",
]


class RunFailedPayload(BaseModel):
    model_config = ConfigDict(strict=True, extra="forbid", frozen=True)

    code: RunErrorCode
    retryable: bool

    @model_validator(mode="after")
    def validate_failure_tuple(self) -> Self:
        if self.retryable and self.code not in (
            "model_unavailable",
            "dependency_unavailable",
        ):
            raise ValueError("invalid failure code/retryable tuple")
        return self


class ChatFailure(RunFailedPayload):
    status: Literal["failed"]
