# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kokoro/platform/capability/v1/capability_catalog.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kokoro.platform.capability.v1.capability_catalog_pb2 as kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2


class HubCatalogService(Protocol):
    async def freeze_catalog(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_catalog_publication(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HubCatalogServiceASGIApplication(ConnectASGIApplication[HubCatalogService]):
    def __init__(self, service: HubCatalogService | AsyncGenerator[HubCatalogService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kokoro.platform.capability.v1.HubCatalogService/FreezeCatalog": Endpoint.unary(
                    method=MethodInfo(
                        name="FreezeCatalog",
                        service_name="kokoro.platform.capability.v1.HubCatalogService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.freeze_catalog,
                ),
                "/kokoro.platform.capability.v1.HubCatalogService/GetCatalogPublication": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCatalogPublication",
                        service_name="kokoro.platform.capability.v1.HubCatalogService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_catalog_publication,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.platform.capability.v1.HubCatalogService"


class HubCatalogServiceClient(ConnectClient):
    async def freeze_catalog(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FreezeCatalog",
                service_name="kokoro.platform.capability.v1.HubCatalogService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_catalog_publication(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCatalogPublication",
                service_name="kokoro.platform.capability.v1.HubCatalogService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class HubRuntimeService(Protocol):
    async def resolve_execution_assembly(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def fetch_skill_artifact(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactRequest, ctx: RequestContext) -> AsyncIterator[kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HubRuntimeServiceASGIApplication(ConnectASGIApplication[HubRuntimeService]):
    def __init__(self, service: HubRuntimeService | AsyncGenerator[HubRuntimeService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kokoro.platform.capability.v1.HubRuntimeService/ResolveExecutionAssembly": Endpoint.unary(
                    method=MethodInfo(
                        name="ResolveExecutionAssembly",
                        service_name="kokoro.platform.capability.v1.HubRuntimeService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.resolve_execution_assembly,
                ),
                "/kokoro.platform.capability.v1.HubRuntimeService/FetchSkillArtifact": Endpoint.server_stream(
                    method=MethodInfo(
                        name="FetchSkillArtifact",
                        service_name="kokoro.platform.capability.v1.HubRuntimeService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.fetch_skill_artifact,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.platform.capability.v1.HubRuntimeService"


class HubRuntimeServiceClient(ConnectClient):
    async def resolve_execution_assembly(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResolveExecutionAssembly",
                service_name="kokoro.platform.capability.v1.HubRuntimeService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def fetch_skill_artifact(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="FetchSkillArtifact",
                service_name="kokoro.platform.capability.v1.HubRuntimeService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class CapabilityCatalogProjectionService(Protocol):
    async def project_catalog(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_projection_receipt(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class CapabilityCatalogProjectionServiceASGIApplication(ConnectASGIApplication[CapabilityCatalogProjectionService]):
    def __init__(self, service: CapabilityCatalogProjectionService | AsyncGenerator[CapabilityCatalogProjectionService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kokoro.platform.capability.v1.CapabilityCatalogProjectionService/ProjectCatalog": Endpoint.unary(
                    method=MethodInfo(
                        name="ProjectCatalog",
                        service_name="kokoro.platform.capability.v1.CapabilityCatalogProjectionService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.project_catalog,
                ),
                "/kokoro.platform.capability.v1.CapabilityCatalogProjectionService/GetProjectionReceipt": Endpoint.unary(
                    method=MethodInfo(
                        name="GetProjectionReceipt",
                        service_name="kokoro.platform.capability.v1.CapabilityCatalogProjectionService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_projection_receipt,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.platform.capability.v1.CapabilityCatalogProjectionService"


class CapabilityCatalogProjectionServiceClient(ConnectClient):
    async def project_catalog(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ProjectCatalog",
                service_name="kokoro.platform.capability.v1.CapabilityCatalogProjectionService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_projection_receipt(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProjectionReceipt",
                service_name="kokoro.platform.capability.v1.CapabilityCatalogProjectionService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class HubCatalogServiceSync(Protocol):
    def freeze_catalog(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_catalog_publication(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HubCatalogServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: HubCatalogServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kokoro.platform.capability.v1.HubCatalogService/FreezeCatalog": EndpointSync.unary(
                    method=MethodInfo(
                        name="FreezeCatalog",
                        service_name="kokoro.platform.capability.v1.HubCatalogService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.freeze_catalog,
                ),
                "/kokoro.platform.capability.v1.HubCatalogService/GetCatalogPublication": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCatalogPublication",
                        service_name="kokoro.platform.capability.v1.HubCatalogService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_catalog_publication,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.platform.capability.v1.HubCatalogService"


class HubCatalogServiceClientSync(ConnectClientSync):
    def freeze_catalog(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FreezeCatalog",
                service_name="kokoro.platform.capability.v1.HubCatalogService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FreezeCatalogResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_catalog_publication(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCatalogPublication",
                service_name="kokoro.platform.capability.v1.HubCatalogService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetCatalogPublicationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class HubRuntimeServiceSync(Protocol):
    def resolve_execution_assembly(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def fetch_skill_artifact(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactRequest, ctx: RequestContext) -> Iterator[kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HubRuntimeServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: HubRuntimeServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kokoro.platform.capability.v1.HubRuntimeService/ResolveExecutionAssembly": EndpointSync.unary(
                    method=MethodInfo(
                        name="ResolveExecutionAssembly",
                        service_name="kokoro.platform.capability.v1.HubRuntimeService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.resolve_execution_assembly,
                ),
                "/kokoro.platform.capability.v1.HubRuntimeService/FetchSkillArtifact": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="FetchSkillArtifact",
                        service_name="kokoro.platform.capability.v1.HubRuntimeService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.fetch_skill_artifact,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.platform.capability.v1.HubRuntimeService"


class HubRuntimeServiceClientSync(ConnectClientSync):
    def resolve_execution_assembly(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResolveExecutionAssembly",
                service_name="kokoro.platform.capability.v1.HubRuntimeService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ResolveExecutionAssemblyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def fetch_skill_artifact(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="FetchSkillArtifact",
                service_name="kokoro.platform.capability.v1.HubRuntimeService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.FetchSkillArtifactResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class CapabilityCatalogProjectionServiceSync(Protocol):
    def project_catalog(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_projection_receipt(self, request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptRequest, ctx: RequestContext) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class CapabilityCatalogProjectionServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: CapabilityCatalogProjectionServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kokoro.platform.capability.v1.CapabilityCatalogProjectionService/ProjectCatalog": EndpointSync.unary(
                    method=MethodInfo(
                        name="ProjectCatalog",
                        service_name="kokoro.platform.capability.v1.CapabilityCatalogProjectionService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.project_catalog,
                ),
                "/kokoro.platform.capability.v1.CapabilityCatalogProjectionService/GetProjectionReceipt": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetProjectionReceipt",
                        service_name="kokoro.platform.capability.v1.CapabilityCatalogProjectionService",
                        input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptRequest,
                        output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_projection_receipt,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.platform.capability.v1.CapabilityCatalogProjectionService"


class CapabilityCatalogProjectionServiceClientSync(ConnectClientSync):
    def project_catalog(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ProjectCatalog",
                service_name="kokoro.platform.capability.v1.CapabilityCatalogProjectionService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.ProjectCatalogResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_projection_receipt(
        self,
        request: kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProjectionReceipt",
                service_name="kokoro.platform.capability.v1.CapabilityCatalogProjectionService",
                input=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptRequest,
                output=kokoro_dot_platform_dot_capability_dot_v1_dot_capability__catalog__pb2.GetProjectionReceiptResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
