# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kokoro/agent/execution/v1/agent_execution_evidence.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kokoro.agent.execution.v1.agent_execution_evidence_pb2 as kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2


class AgentExecutionEvidenceService(Protocol):
    async def pull_durable_execution_evidence(self, request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_durable_execution_evidence(self, request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_run_durable_checkpoint(self, request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AgentExecutionEvidenceServiceASGIApplication(ConnectASGIApplication[AgentExecutionEvidenceService]):
    def __init__(self, service: AgentExecutionEvidenceService | AsyncGenerator[AgentExecutionEvidenceService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kokoro.agent.execution.v1.AgentExecutionEvidenceService/PullDurableExecutionEvidence": Endpoint.unary(
                    method=MethodInfo(
                        name="PullDurableExecutionEvidence",
                        service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                        input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceRequest,
                        output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.pull_durable_execution_evidence,
                ),
                "/kokoro.agent.execution.v1.AgentExecutionEvidenceService/GetDurableExecutionEvidence": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDurableExecutionEvidence",
                        service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                        input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceRequest,
                        output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_durable_execution_evidence,
                ),
                "/kokoro.agent.execution.v1.AgentExecutionEvidenceService/GetRunDurableCheckpoint": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRunDurableCheckpoint",
                        service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                        input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointRequest,
                        output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_run_durable_checkpoint,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.agent.execution.v1.AgentExecutionEvidenceService"


class AgentExecutionEvidenceServiceClient(ConnectClient):
    async def pull_durable_execution_evidence(
        self,
        request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PullDurableExecutionEvidence",
                service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceRequest,
                output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_durable_execution_evidence(
        self,
        request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDurableExecutionEvidence",
                service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceRequest,
                output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_run_durable_checkpoint(
        self,
        request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRunDurableCheckpoint",
                service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointRequest,
                output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class AgentExecutionEvidenceServiceSync(Protocol):
    def pull_durable_execution_evidence(self, request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_durable_execution_evidence(self, request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_run_durable_checkpoint(self, request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AgentExecutionEvidenceServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AgentExecutionEvidenceServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kokoro.agent.execution.v1.AgentExecutionEvidenceService/PullDurableExecutionEvidence": EndpointSync.unary(
                    method=MethodInfo(
                        name="PullDurableExecutionEvidence",
                        service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                        input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceRequest,
                        output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.pull_durable_execution_evidence,
                ),
                "/kokoro.agent.execution.v1.AgentExecutionEvidenceService/GetDurableExecutionEvidence": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDurableExecutionEvidence",
                        service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                        input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceRequest,
                        output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_durable_execution_evidence,
                ),
                "/kokoro.agent.execution.v1.AgentExecutionEvidenceService/GetRunDurableCheckpoint": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRunDurableCheckpoint",
                        service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                        input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointRequest,
                        output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_run_durable_checkpoint,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.agent.execution.v1.AgentExecutionEvidenceService"


class AgentExecutionEvidenceServiceClientSync(ConnectClientSync):
    def pull_durable_execution_evidence(
        self,
        request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PullDurableExecutionEvidence",
                service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceRequest,
                output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.PullDurableExecutionEvidenceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_durable_execution_evidence(
        self,
        request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDurableExecutionEvidence",
                service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceRequest,
                output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetDurableExecutionEvidenceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_run_durable_checkpoint(
        self,
        request: kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRunDurableCheckpoint",
                service_name="kokoro.agent.execution.v1.AgentExecutionEvidenceService",
                input=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointRequest,
                output=kokoro_dot_agent_dot_execution_dot_v1_dot_agent__execution__evidence__pb2.GetRunDurableCheckpointResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
