# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kokoro/agent/control/v2/session_agent_control.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kokoro.agent.control.v2.session_agent_control_pb2 as kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2


class SessionAgentControlRecoveryService(Protocol):
    async def get_run_resume_receipt_events(self, request: kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SessionAgentControlRecoveryServiceASGIApplication(ConnectASGIApplication[SessionAgentControlRecoveryService]):
    def __init__(self, service: SessionAgentControlRecoveryService | AsyncGenerator[SessionAgentControlRecoveryService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kokoro.agent.control.v2.SessionAgentControlRecoveryService/GetRunResumeReceiptEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRunResumeReceiptEvents",
                        service_name="kokoro.agent.control.v2.SessionAgentControlRecoveryService",
                        input=kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsRequest,
                        output=kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_run_resume_receipt_events,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.agent.control.v2.SessionAgentControlRecoveryService"


class SessionAgentControlRecoveryServiceClient(ConnectClient):
    async def get_run_resume_receipt_events(
        self,
        request: kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRunResumeReceiptEvents",
                service_name="kokoro.agent.control.v2.SessionAgentControlRecoveryService",
                input=kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsRequest,
                output=kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class SessionAgentControlRecoveryServiceSync(Protocol):
    def get_run_resume_receipt_events(self, request: kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsRequest, ctx: RequestContext) -> kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SessionAgentControlRecoveryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SessionAgentControlRecoveryServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kokoro.agent.control.v2.SessionAgentControlRecoveryService/GetRunResumeReceiptEvents": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRunResumeReceiptEvents",
                        service_name="kokoro.agent.control.v2.SessionAgentControlRecoveryService",
                        input=kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsRequest,
                        output=kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_run_resume_receipt_events,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kokoro.agent.control.v2.SessionAgentControlRecoveryService"


class SessionAgentControlRecoveryServiceClientSync(ConnectClientSync):
    def get_run_resume_receipt_events(
        self,
        request: kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRunResumeReceiptEvents",
                service_name="kokoro.agent.control.v2.SessionAgentControlRecoveryService",
                input=kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsRequest,
                output=kokoro_dot_agent_dot_control_dot_v2_dot_session__agent__control__pb2.GetRunResumeReceiptEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
